# Generated by Django 6.0.5 on 2026-05-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва апартаментів')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('capacity', models.IntegerField(default=1, verbose_name='Місткість')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Апартаменти',
                'verbose_name_plural': 'Апартаменти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії номерів',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('check_in', models.DateField(verbose_name='Дата заїзду')),
                ('check_out', models.DateField(verbose_name='Дата виїзду')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.apartments', verbose_name='Апартаменти')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apartments',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='booking_app.category', verbose_name='Категорія'),
        ),
    ]
